openapi: "3.0.0"

info:
  version: 1.0.0
  title: klaxoon-bookmarks

paths:

  /bookmarks:
    x-swagger-router-controller: controller
    get:
      summary: get all bookmarks
      operationId: getBookmarks
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An array of bookmarks
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Bookmarks"

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Create a pet
      operationId: createBookmark

      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /bookmarks/{id}:
    x-swagger-router-controller: controller
    get:
      summary: get given bookmark
      operationId: getBookmark
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the bookmark
          schema:
            type: string

      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bookmark"

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
        summary: update given bookmark
        operationId: updateBookmark
        parameters:
          - name: id
            in: path
            required: true
            description: The id of the bookmark
            schema:
              type: string
  
        responses:
          204:
            description: No content response
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
  
    delete:
      summary: delete given bookmark
      operationId: deleteBookmark
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the bookmark
          schema:
            type: string
  
      responses:
        204:
          description: No content response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
